Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: serverless-blog-post-images

  RedisCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: cache.t2.micro
      Engine: redis
      NumCacheNodes: 1